// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrsqndpdcacajdjjkdvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyc3FuZHBkY2FjYWpkamprZHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Mjk3MTcsImV4cCI6MjA3NzQwNTcxN30.GCDJbkonRyxWZ3sjxWjw4PLNsQ_KComjfwQONdcDRu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});